### ISSUE TITLE
Slow scrolling on iOS when using Plus Editor

### ISSUE THREAD

**Issue by christianhans** [standardnotes/mobile#108]
Hi,

When using the Plain editor on iOS scrolling is butter smooth. When using extended/plus editors scrolling is painfully slow. I assume it has to do with the plus editor being embedded inside an iFrame.

I'm on iOS 12.1.1 / iPhone XS.

Best
Christian

**Comment by mobitar** [comment]
The Plus editor itself is notorious for having awkward scrolling, due to its architecture. But the other editors shouldn't have the same issue. Maybe not as buttery smooth as native scrolling, but probably not as degraded as the Plus editor. Let me know if you've seen anything particularly bad in any of the other editors.

**Comment by christianhans** [comment]
I didn’t describe the problem well enough. :-)

What I’m referring to is the momentum of native iOS scrolling. I.e. when you drag and let go it continues to scroll. The plain editor does do that. The extended editors such as the Simple Markdown Editor don’t do that.

Best
Christian

**Comment by mobitar** [comment]
Ah, I see. I've just tested all the editors on iOS and can confirm. I'll have to see why this is happening, and if there's a way around it. They are iFrames afterall, but it could be some nesting issue.

**Comment by mobitar** [comment]
This issue should now be fixed. Restart your app and it should take effect.

If it still doesn't, likely a cache issue. Might just have to keep trying or find a way to clear your cache (uninstall and reinstall the app, if nothing else.)
