### ISSUE TITLE
[iOS] [3.0.0-Beta3] Previously created Smart Tags don't show up after upgrade

### ISSUE THREAD

**Issue by christianhans** [standardnotes/mobile#123]
After installing 3.0.0 Beta3 from Testflight my previously created Smart Tags don't appear. I had to sign out and sign in again. Now my own Smart Tags appear but I have the Archived Smart Tag twice (one of them doesn't show any notes).

**Comment by mobitar** [comment]
That sounds right. Previously smart tags were not picked up by mobile because it had no use for them. Ideally we'd run a migration so that we can download these from the server. I'll make a note of this. You're seeing the Archived tag twice because Archived is now a default system smart tag, so you'll have to delete your custom Archived tag.

**Comment by mobitar** [comment]
Migration has been added in 3.0.0 release, so they should be downloaded now on first launch.
