### ISSUE TITLE
[Android] Issue scrolling tag lists

### ISSUE THREAD

**Issue by HansCronau** [standardnotes/mobile#136]
First of all: I love the version 3 update!

One issue I do run into is that the tag lists are very sensitive and seem to highjack scrolling.

How to reproduce:
Have a bunch of tags ready and make/open a note. Open the right side menu and try to scroll it up and down, starting your finger on one of the tags listed and moving up/down.

Expected behaviour:
The menu scrolls along.

Behaviour observed instead (50/50):
The menu does not scroll along.

In both cases the tag touched first may get a highlight for a short moment.

This is the case for tag lists both in the main menu (left) and in the note menu (right).

**Comment by mobitar** [comment]
Glad to hear you're enjoying the update! How many tags do you have? I haven't seen this behavior with testing of about 100 tags. But having a lot more may cause problems. Let me know if this is the case and I can investigate further.

**Comment by HansCronau** [comment]
Hi. I think I have figured it out. Could it be the side bar registering a horizontal drag first and then ignoring any vertical movement? Especially when using thumbs (you know, those stumps that are particularly good at dragging circles around their joints) I noticed that the side bar sometimes didn't respond. I then checked by intentionally initiating drags diagonally. This seems to confirm the theory.

**Comment by mobitar** [comment]
Hmm, it's possible, if you're not scrolling directly vertically. But I haven't experienced this. Could vary person to person though.

**Comment by Fohroer** [comment]
I sometimes notice the same bug on my phone.

**Comment by bryvin** [comment]
It seems the reason this happens is the Note's sidemenu can be swiped open/closed by essentially flicking it to or from the edge of the screen.

I have to purposely try to slide it sideways for this issue to take effect. Can any of the original reporters confirm if the newer version of the app help with this behavior for you? We did recently change out the Scrolling view for the side menu.

**Comment by Fohroer** [comment]
Please excuse me for being lazy ass. Here is video with demonstation. The firmware is the same. The version is latest (Version 3.0.18) from Google Play.
Here is video: https://github.com/Fohroer/files (7z 2 part no password)

**Comment by HansCronau** [comment]
Hi @bryvin! Thanks for looking into it. I'm on version 3.0.17, but I'm still able to reproduce the issue. More or less vertical thumb movement still sometimes registers as a horizontal movement first. Now and then I actually spot the sidebar slightly moving horizontally. If my thumb started on a tag, the tag briefly highlights.

**Comment by pcrockett** [comment]
I have to wonder if screen quality isn't playing a role here too. Each phone model probably has varying levels of touch input sensitivity and accuracy, and you may have to move your thumb with a lot more intentionality with some models than others. Operating system might also play a role here: I'm using [/e/][1] instead of stock Android.

That said, I have bumped up against this so much that it seems no level of intentionality can get my finger to move straight enough up and down 100% of the time. Maybe 50% of the time when I touch the tag list, it registers as a horizontal movement, and I can't seem to find a good method to convince it to scroll vertically. I just have to try and try again until it works.

I also wonder if it would help to bring the tag drawer in and out using a well-defined _gesture_ sort of event, rather than the smooth _draggy_ behavior that's currently there.

[1]: https://e.foundation/products/

**Comment by HansCronau** [comment]
@pcrockett I'm using Lineage and have observed this behaviour on phones from Huawei, LG, and OnePlus on which other apps did not have similar issues.

**Comment by Fohroer** [comment]
https://goblinrefuge.com/mediagoblin/u/fohroer/m/bug-report/
If you wish to view video vith bug demonstration normally.

**Comment by radko93** [comment]
Thank you for the report, this should fixed in the latest version.
