### ISSUE TITLE
[Android] Downgrading lock to only fingerprint on fingerprint+passcode lock

### ISSUE THREAD

**Issue by NielsdeWaal** [standardnotes/mobile#137]
Disclaimer, I haven't tested this on other devices, but I found this possible issue today.

My setup:
- Fingerprint (Immediately)
- Passcode (On Quit)

Bug:
When I open the app I have to enter my passcode and fingerprint to access my notes.
However, when I have this screen open, it seems to be possible to downgrade this lock to a version where I only have to enter my fingerprint and can therefore bypass the passcode.

Steps to reproduce:
1. Open app
2. When on the screen where it asks for both fingerprint and passcode, press return.
3. After pressing return the screen should give a message like: "Application Locked.", with an unlock button.
4. Close the app, but do not fully stop the process (by using the multitasking drawer)
5. Open the app again

After opening the app for the second time it only asks for my fingerprint and not my passcode, which I haven't ever entered at this point.

**Comment by mobitar** [comment]
Hey @NielsdeWaal, thanks for the detailed report. I've tested your steps and can partially replicate it. After step 2, I press the hardware back button on Android instead, as pressing return doesn't do anything. Then I get the screen where it says Application Locked. Then I close out and come back in, and indeed, it only asks for my fingerprint. However, after I authenticate with my fingerprint, the app unlocks, but all my items say "Missing Keys". This is because the item keys are encrypted with your passcode, which was never entered.

Are you also seeing this? If not, you may have Device Storage Encryption disabled. 

In any case, this first half of this is definitely still an issue that needs to be fixed. Thanks for the heads up!

**Comment by NielsdeWaal** [comment]
@mobitar,
My notes seem to all be decrypted after I enter my fingerprint.
I've not been able to find out whether Device Storage Encryption is disabled, my guess is that this should be mentioned in the settings, but I can't seem to find it.

"Encryption Status" indicates that everything is encrypted, the same is true for "Security".
If you would be able to tell me where I can find this, then I could try and replicate what you are seeing.

**Comment by mobitar** [comment]
Yes it's in the settings, in the Security section, as the first item, right above "Enable/Disable Passcode Lock".

**Comment by NielsdeWaal** [comment]
Then I can confirm that my storage encryption is enabled.
(Or the wording is slightly confusing, but I get the question whether I want to disable or not)

**Comment by mobitar** [comment]
What version of the app is this btw? I'm testing with 3.0.3. If you are using this version already, can you elaborate on step 2, where you press return? On my end, pressing return doesn't do anything but dismiss the keyboard. You mean return on the keyboard right? Or do you mean the hardware back button for Android?

**Comment by NielsdeWaal** [comment]
Yeah, I'm using 3.0.3.
I also made the mistake of not mentioning that I pressed the return button twice.
Once to close the keyboard and the second time to go to the screen stating that the application is locked.

**Comment by mobitar** [comment]
This issue is now fixed in 3.0.4, which was just released.
