### ISSUE TITLE
Restoring iCloud backup to new iPhone caused me to lose all of my notes

### ISSUE THREAD

**Issue by aaronraimist** [standardnotes/mobile#18]
I'm sure I probably just didn't do this properly but it is a little scary to think that this can happen. I got a new iPhone today and I use iCloud backup to restore this new phone to be as close as possible to my old phone. When I opened Standard Notes all of the notes showed some kind of error message along the lines of being undecryptable. I didn't screenshot this. I assumed (I think wrongly?) that I just had to log out and back in to Standard Notes and all of my notes would come back. Well they didn't. Instead, I was presented with a list of all of my notes except all of the content was missing.

![image](https://user-images.githubusercontent.com/5855073/32470232-42d7e19a-c31c-11e7-928c-a4cb3e9e7a6c.png)

I picked up my old phone which I hadn't erased yet and saw that the empty state of the notes had already been synced across to the old phone.

I was able to recover because I had a computer with SN on it. So I turned off wifi to prevent syncing and opened SN on my computer and then exported the archive and was able to reimport. I think I have all of my notes back.

I just wanted to make sure you knew this was possible. I assume if I hadn't logged out on the new phone all of the decryption keys would have worked their way down to my phone eventually but I don't think this kind of major error should really be able to happen, no matter what mistake user makes.

**Comment by aaronraimist** [comment]
I just saw that you released 2.0.2 3 hours ago. Was that released to solve this issue?

**Comment by mobitar** [comment]
Hey Aaron, sorry you experienced this, and yes 2.0.2 was released to address this exact issue. We keep backups of our database, so even if you didn't have your own backups, we would have been able to restore your notes.

Regarding why this happens, when you restore your phone from an iCloud backup, it also restores your apps, including any files the app has saved (for us this includes your notes). However, it does not restore your keychain, which is where we store your decryption keys and account info.

What happens is when you open the app without they keys, the app fails to decrypt any of the items. Naturally, you think to sign in to restore access. However, when you sign in, any existing offline notes are synced up to the server, so that you don't lose them.

In this case, the app would sync up items that were not decrypted properly, thus causing the issue you saw. The solution was simple of course: never sync up items that aren't decrypted properly. So you should never see this issue again on any platform.

Apologies again for the fright. We create nightly backups of our database going back up to 30 days, so there's no real danger of data loss for online accounts. 

[Version 2.0.3](https://github.com/standardnotes/desktop/releases/tag/v2.0.3) of the desktop app introduces automated local backups as well.

**Comment by aaronraimist** [comment]
Alright sounds good. Thanks for the info and for releasing the update so quickly after the new phones came out.
