### ISSUE TITLE
Remove iOS automatic capitalization for titles

### ISSUE THREAD

**Issue by daylightbrightledlight** [standardnotes/mobile#19]
When typing in the note's title section on iOS, the first letter of words are automatically capitalized.

Please remove the automatic capitalization. I find this extremely annoying and unnecessary. It is inconsistent with the Desktop app. I also naturally press the Shift key when I want a capital letter.

I find capitalizing every word in titles annoying due to the inconsistencies in English. This is why I prefer Wikipedia's approach to titles.

**Comment by mobitar** [comment]
When in doubt about a feature, I always ask "what is the more standard form of this?" And in this case, you're right, auto-capitalizing titles is not standard, but custom behavior. It's obviously tricky since many people are now accustomed to this, so removing it will be painful for some, who might even revolt enough to leave a negative review. So I'll say that I'll intend to remove this, but it's definitely tricky.

**Comment by daylightbrightledlight** [comment]
@mobitar I understand that this is a tricky decision. Perhaps the earlier this is implemented, the fewer people will find it painful. I do believe that there are only a very few individuals will find it painful, and the majority of the iOS users will appreciate typing without the automatic capitalization getting in the way.

**Comment by mobitar** [comment]
I believe this was fixed some time ago.
