### ISSUE TITLE
Regression: error exporting backup

### ISSUE THREAD

**Issue by KLaurence** [standardnotes/mobile#461]
When exporting data and saving it to disk, an unknown error occurs. About its details, I don't think that the app's builtin error reporting reports the error even when enabled. I'm also not aware of any logs that the app generates that can help describe the error.

The steps to reproduce this error are:
1. Open Standard Notes
2. Click "Encrypted"/"Decrypted" next to "Export Data"
3. If prompted, grant storage permission
4. Click "Save to Disk"

The issue is present in v3.6.21. The last version that doesn't have this issue is v3.6.13. #444 might be related.

**Comment by JaspalSuri** [comment]
Hi @KLaurence,

I'm afraid that I was unable to reproduce this issue. What is the error that occurs when you try to save the exported file locally? Does an error message appear? Does the backup simply not appear in the `Downloads` folder? Are there any issues with the files?

Which version of Android are you using and which files app are you using to locate the files? I noticed that the Files app by Google required me to pull-to-refresh in order to update the list of files listed in the `Downloads` folder.

**Comment by KLaurence** [comment]
Hello, @JaspalSuri. The error that occurs is not specified upon by the app. The app just says that "there was an issue exporting your backup". Pressing the OK button doesn't show any other messages.

I'm currently using Android 10 with the [Material Files](https://github.com/zhanghai/MaterialFiles) app with hidden files shown and has a pull-to-refresh feature. With all that, the file doesn't show up in `/Downloads`.

The issue still occurs for me in v3.6.21.

**Comment by JaspalSuri** [comment]
Hi @KLaurence, thank you so much for those details! I'll get in touch with the dev team on this for their guidance on how to proceed from here.

**Comment by KLaurence** [comment]
v3.6.23's changelog lists improvements for backup error logs. Sadly, the backup error remains unspecific in v3.6.23.

I've realized regardless that I haven't shown a screenshot of that issue message, so here's a screenshot of it:

![Unspecific-backup-issue-message-screenshot](https://user-images.githubusercontent.com/6565795/132111875-581c54a9-a7fb-4abf-9386-f85936f27dc6.jpg)

**Comment by JaspalSuri** [comment]
>v3.6.23's changelog lists improvements for backup error logs. Sadly, the backup error remains unspecific in v3.6.23.

Sorry about that - that's for the logs that are sent via Bugsnag to us via the apps (when a user as opted-in). This will hopefully help us figure out what is going wrong in order to bring us closer to fixing the issue. 

Can you (1) opt-in to the setting (it's located at the bottom of the settings page of the mobile app), (2) reproduce the error, and then (3) comment back with (a) which device you're using and at (b) which time you ran into the issue, either relative to the time you posted your comment or by including your local time zone (or UTC for a bit more privacy)?

**Comment by KLaurence** [comment]
Sure, I have no problem with opting in. A problem though is that when I reproduce the error, it doesn't seem like SN uses the network to report the error. 

Regardless of whether my firewall app blocks SN's network usage (though I've set it up to not block it), the firewall doesn't list any network usage from SN. I'm aware of SN's F-Droid version not reporting errors, but I've downloaded the APK from this repo's Releases section.

I don't think the error not being reported is intentional, but I'm not sure what to do next. Should I post a video reproducing the error?

**Comment by JaspalSuri** [comment]
That's strange; thank you for letting us know. While appreciated, a video won't be necessary in this case. (cc @antsgar)

**Comment by smc777-0** [comment]
I am experiencing this issue also on v3.6.23 on my phone running android 10 lineage 17.1
Upon trying to export backup to local disk I get the same error message as noted in previous comment https://github.com/standardnotes/mobile/issues/461#issuecomment-913066788
Export to email opens email application but with no attachment.

However this function does seem to work fine on my Samsung tablet running android 11 so maybe some permissions issue on the os side?

I have rolled back to 3.6.13 and this feature seems to be working as suggested.

**Comment by JaspalSuri** [comment]
Hi @smc777-0, thank you for testing multiple devices that are using different versions of Android. Hopefully that will help us get closer to finding a viable solution (that doesn't involve a rollback unless necessary).

**Comment by Saldef** [comment]
Hi @JaspalSuri I am experiencing the same issue here, running v3.6.24 on Android 10 Lineage 17.1 on a XiaoMi phone, email also doesn't include any attachment.

**Comment by KLaurence** [comment]
This bug is gone for me in v3.9.2.
