### ISSUE TITLE
[UI] Icon of Options button in note view

### ISSUE THREAD

**Issue by FiveYellowMice** [standardnotes/mobile#48]
Currently the Options button in note view have a tag icon, this might cause confusion because the button does not only open a tag editor, but also a list of actions a user could take. My suggestion would be changing the icon to "three dots" or a gear.

**Comment by mobitar** [comment]
The issue was when we had three dots, users didn't know how to add tags. Was a reoccurring source of confusion. Given that users will need to add tags, they will eventually see the other options present there and associate that button. I guess it can be confusing depending on what you're looking for. Just takes once though to clear it up.

**Comment by FiveYellowMice** [comment]
OK, that does make sense.
