### ISSUE TITLE
Subscription Via Google Play Billing

### ISSUE THREAD

**Issue by katehowler** [standardnotes/mobile#72]
What do you think of adding support for [Google Play Billing](https://developer.android.com/google/play/billing/billing_overview) for in-app-purchases (IAP) for subscribing [Extended](https://standardnotes.org/extensions) on [Android](https://www.android.com/) devices?

**Comment by mobitar** [comment]
It's tricky because currently the way to manage your Extended extensions, like install/uninstall, requires the web or desktop app. Adding mobile app billing would require us to build a whole solution around installing extensions from mobile, which would be a huge undertaking. For now, it's still a distant goal.

**Comment by katehowler** [comment]
Oh, I see.
