### ISSUE TITLE
Improving Search

### ISSUE THREAD

**Issue by lokesh-krishna** [standardnotes/mobile#8]
Could it be possible to highlight instances of the searched term within the notes? Would be a huge time-saver.

**Comment by mobitar** [comment]
This would be a long-term add, as it's not trivial.

**Comment by shola** [comment]
I've been tinkering with a prototype to deliver this feature request, and I'd like to polish it up if the behavior and implementation are on the right track. I had to make some assumptions to get a prototype working, and added code comments to explain my reasoning. Have a look at the screenshots and **[this prototype branch](https://github.com/shola/mobile/tree/highlight-searchterm)** and let me know what your thoughts are.

![simulator screen shot - iphone 8 plus - 2018-03-13 at 13 09 24](https://user-images.githubusercontent.com/59469/37447996-b673e0de-27e1-11e8-9adc-4f79a5e8aad0.png)
![simulator screen shot - iphone 8 plus - 2018-03-13 at 13 25 00](https://user-images.githubusercontent.com/59469/37447997-b68dd12e-27e1-11e8-87f9-99b8e6c252cf.png)

**Comment by mobitar** [comment]
@shola this is pretty cool! You did it with less lines of code than I'd expect too. Although, I wish we could do this for the web/desktop app before we do it for mobile. Because doing it for mobile first is going to create a barrage of "why isn't this available on desktop??" (In note searching).

My concern with this is, what if the search term is not in the first two lines? Sort of a confusing interface then. Users will begin demanding that we clip out the relevant part from the note and display it in the results, prefixed with a "..."

Also, and this is where I'm torn: I haven't yet decided that mobile will be a "power" app. I'm reluctant to add features like this because it opens the door for more and more advanced features. The number one thing about mobile for me is that it has to be easy to maintain. You could have a 5 star app otherwise, but if you add in this one feature, and it doesn't work, you'll get 1-2 stars. So it's not always worth it.

If you're up for it, I'd love your help on adding in-note search highlighting on web/desktop. I think that would be much more useful.

**Comment by sidmint** [comment]
I want to highlight the importance of this feature first: If you have a long note and you search for a term then the whole note comes in the result without highlighting where the term is. Now this is pretty much not useful at all for long notes specially, as i can't search that small term in that long note anyway afterwards easily. And personally, since I've many long notes I use this feature and depend on it very much in Colornote currently.

**Comment by sidmint** [comment]
I think what @shola has demontrated above may not be appropriate though still very useful for when the results are few. If the results are many then how many of them will be shown on the top? One will have to go inside the note and attend to highlighted results individually anyway, as indicated in #83. But unlike #83, one should not be forced to search inside each note individually but that should happen after searching all the notes and then opening a result-note, and then the #83 methodology must be used.
